<b>Forward Propagation</b>

Passing single input

In [1]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction  

In [2]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


Passing multiple inputs - works using dot product / weighted sum

In [3]:
def w_sum(a, b):
    assert (len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

In [4]:
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

In [5]:
weights = [0.1, 0.2, 0]

In [6]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

print(pred)

0.9800000000000001


In [7]:
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


Predicting multiple outputs from single inputs - works similar but with element multiplication

In [8]:
weights = [0.3, 0.2, 0.9]

wlrec = [0.65, 0.8, 0.9]

input = wlrec[0]

def ele_mul (number, vector):
    output = [0,0,0]
    assert (len(output) == len(vector))

    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

def neural_network(inputs, weights):
    pred = ele_mul(input, weights)
    return pred

pred = neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


Predicting with multiple inputs and outputs - uses weigthed sum and vector maths multiplication of the vector resulting from the weighted sum with each vector of the mtaix formed for each subsewuent weight.

In [9]:
def w_sum(a,b):
    assert (len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert (len(vect) == len(matrix))
    output = [0,0,0]

    for i in range(len(vect)):
        output[1] = w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

weights = [[0.1, 0.1, -0.3], #hurt?
           [0.1, 0.2, 0.0],  #win?
           [0.0, 1.3, 0.1]   #sad?
           ]

pred = neural_network(input, weights)
print(pred)

[0, 0.9650000000000001, 0]


Stacked Networks - Multiple layers of the neural network

In [10]:
ih_wgt = [ 
    [0.1, 0.2, -0.1], # hid[0]
    [-0.1,0.1, 0.9],  # hid[1] 
    [0.1, 0.4, 0.1]   # hid[2]
    ] 

hp_wgt = [
    [0.3, 1.1, -0.3], # hurt?
    [0.1, 0.2, 0.0],  # win? 
    [0.0, 1.3, 0.1]   # sad?
    ] 

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = vect_mat_mul(input,weights[0]) 
    pred = vect_mat_mul(hid,weights[1]) 
    return pred

toes = [8.5, 9.5, 9.9, 9.0] 
wlrec = [0.65,0.8, 0.8, 0.9] 
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0],wlrec[0],nfans[0]] 
pred = neural_network(input,weights)
print(pred)

[0, 1.599, 0]


In [15]:
# Numpy Version
import numpy as np

#toes % win # fans
ih_wgt = np.array([
    [0.1, 0.2, -0.1], # hid[0]
    [-0.1, 0.1, 0.9], # hid[1]
    [0.1, 0.4, 0.1]   # hid[2]
]).T

# hid[0] hid[1] hid[2]
hp_wgt = np.array([
[0.3, 1.1, -0.3], # hurt?
[0.1, 0.2, 0.0],  # win?
[0.0, 1.3, 0.1]   # sad?
]).T

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)
print(pred)

[0.2135 0.145  0.5065]


Primer on numpy

In [1]:
import numpy as np

a = np.array([0,1,2,3]) 
b = np.array([4,5,6,7]) 
c = np.array([[
    0,1,2,3],
    [4,5,6,7]
])
d = np.zeros((2,4))
e = np.random.rand(2,5)

In [2]:
print(a)

[0 1 2 3]


In [3]:
print(b)

[4 5 6 7]


In [4]:
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [5]:
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:

print(e)

[[0.20911777 0.27049794 0.70657005 0.28119026 0.37048116]
 [0.42808061 0.63144237 0.87868343 0.68211992 0.03252528]]


In [7]:
print(a * 0.1)

[0.  0.1 0.2 0.3]


In [8]:
print(c * 0.2)

[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]


In [9]:
print(a * b)

[ 0  5 12 21]


In [10]:
print(a * b * 0.2)

[0.  1.  2.4 4.2]


In [11]:
print(a * c)

[[ 0  1  4  9]
 [ 0  5 12 21]]


In [12]:
# Matrix shapes are incongruent, hence it give error
print(a * e)

ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [18]:
print(a.shape)
print(c.shape)
print("The columns of the left matrix must line up with the rows of the right matrix")

a = np.zeros((2,4)) # 2 by 4 matrix
b = np.zeros((4,3)) # 4 by 3 matrix
c = a.dot(b)
print(c.shape)

(4,)
(2, 4)
The columns of the left matrix must line up with the rows of the right matrix
(2, 3)
